namespace jrintegracaoipm.Models.Enum
{
    public enum TlcCodigo
    {
        ReceitaOrCamentaria = 1,
        ReceitaExtraOrcamentaria = 2,
        PagamentoDeNotaExtraOrcamentaria = 3,
        CancelamentoDeRestosAPagar = 4,
        DepositoBancario = 5,
        DeducaoDeReceita = 6,
        EmissaoDeEmpenho = 7,
        LiquidacaoDeEmpenho = 8,
        PagamentoDeempenho = 9,
        PagamentoDeRestos = 10,
        LancamentoContabilManual = 11,
        DividaFuncada = 12,
        LancamentoPatrimonial = 13,
        PrestacaoDeContasDeRecursoAntecipado = 14,
        AprovacaoDoOrcamento = 15,
        PrevisaoAdicionalDeReceita = 16,
        AlteracaoOrcamentaria = 17,
        DividaAtivaDaTributacao = 18,
        EncerramentoDeContasDeRestos = 19,
        Resgate = 20,
        Aplicacao = 21,
        BloqueioDeDotacao = 22,
        DesbloqueiDeDotacao = 23,
        Precatoria = 24,
        Resposavel = 25,
        TransferenciaBancaria = 26,
        TransferenciaFinanceiraConcedida = 27,
        TransferenciaFinaceiraRecebida = 28,
        MultaDeTransito = 29,
        ReconhecimentoAntecipadoDaReceita = 30,
        ReconhecimentoAntecipadoDaDespesa = 31,
        ApropriacaoDaDespesa = 32,
        Consorcio = 33,
        TransferenciaFinanceiraConcedidaNaEntidadePrefeitura = 34,
        TransferenciaFinanceiraRecebidaNaEntidadeCamara = 35,
        LancamentoAlmoxarifado = 36,
        LancamentoLicitacao = 37,
        InscricaoEmRestosAPagar = 94,
        ImplantacaoDeSaldosDoExercicioAnterior = 98,
        EncerramentoDoExercicio = 99,
        ImplantacaoOrcamentoDoPPA = 100
    }
}
