// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using jrintegracaoipm.Data;

namespace jrintegracaoipm.Migrations
{
    [DbContext(typeof(IntegracaoContext))]
    [Migration("20210405212301_Lancamentos")]
    partial class Lancamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("jrintegracaoipm.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CliCodigo");

                    b.Property<int>("CtlSequencia");

                    b.Property<int>("FlagEstorno");

                    b.Property<DateTime>("LanData");

                    b.Property<string>("LanHistorico");

                    b.Property<double>("LanValor");

                    b.Property<int>("LoaAno");

                    b.Property<string>("PlnCodigoContra");

                    b.Property<int>("PlnTipoPlano");

                    b.Property<int>("PlnTipoPlanoContra");

                    b.Property<string>("Plncodigo");

                    b.Property<int>("TlcCodigo");

                    b.Property<int>("VinCodigo");

                    b.HasKey("Id");

                    b.ToTable("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
